### ISSUE TITLE
FEATURE: Setup visual health checks

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-development-collection#4243]
# Our concept, discussed at the Berlin sprint

## The current state about our GUI Setup at `/setup`

Currently the GUI setup is quite often broken and keeps newcomers from getting a full running Neos to work. Just have a look at all the reported issues, which are just the ones actually reported, we fear that the state is actually worse ^^:

issues reported in the dev collection: https://github.com/neos/neos-development-collection/issues?q=label%3A%22Neos+Setup%22+
issues setup: https://github.com/neos/neos-setup/issues
issues neos setup: https://github.com/neos/setup/issues

One can ask, how we core devs or experienced devs setup neos? Well it can be done fully manually or via the new flow setup commands. This is not only more efficient/faster but also less error prone compared to our flanky web setup.

## We rethought the GUI Setup.

After a long discussion, we concluded, that it currently quite painful to maintain the GUI setup and ensure it works consistently over time on different environments. We took a step back and though about the reasons, we have the GUI setup in the first place.

That came down to mostly two points:

- A: While its a necessity to be confronted with the CLI (see composer) we want to have a visual entry point. Other CMS also allow a visual Setup and new users are probably feeling more welcome there in comparison to a full CLI setup with no visual guide.
- B: For new installations its nice to have the `/setup` endpoint, just to see your first success, that flow can boot and everything is ready. This might be considered a manual basic smoke test.

After crystallizing those two main thoughts, we came up with another way of satisfying them. Instead of a full visual setup, we want to provide an endpoint at `/setup` which you can visit which will tell you basic things about the installation and its current state. For example if no database is setup it will prompt you to do so by proposing the command `./flow setup:database`. This proposed setup hybrid of GUI and CLI (we call it health check) has clear advantages over the current GUI only setup:
- Its not to magical, as it only shows helpful information and steps based on the systems configuration / environment. We plan to make them that helpful, so we core devs will start to use this health check ourselves, so that we will notice ourselves when something breaks.
- Its way less complex in the code and thus can way harder break in the future.
- Its a fun way for people  who dislike the CLI to start using the CLI, as they only need to copy some commands (and the commands are interactive)

## Implementation

On the sprint we managed to implement already most of what we wanted. Now we are left with some little detail problems.
The new healthcheck at `/setup` will look like:

![image](https://github.com/neos/neos-development-collection/assets/85400359/a9a0e7a8-f7bd-4de6-a8f9-074ceff6f059)

- base setup (flow) https://github.com/neos/setup/pull/59
- additional neos adaptor https://github.com/neos/neos-setup/pull/12

**Comment by mhsdesign** [comment]
## Initial brief notes ;)

- Visual entry point is expected
- Setup becomes Health check
- there are no two setups but only the CLI setup

### currently

```                                                                                         
                                                                           ┌──────────────────────────────────────────────┐  
                                                                           │               neos/neos-setup                │  
                                                              │            │                                              │  
                                                              │            │              requires neos/neos              │  
                                                              │            │ provides additional steps: neosRequirements, │  
   ┌────────────────────────────────────────────┐             │            │          administrator, siteimport           │  
   │                                            │             │            │                                              │  
   │                                            │             │            └──────────────────────────────────────────────┘  
   │               neos/cli-setup               │             │                                    │                         
   │                                            │    totally unrelated -                           │                         
   │          newer package (Neos 7.3)          │      no code sharing                         requires                      
   │   requires neos/neos (lives in neos dev    │             │                                    │                         
   │                collection)                 │             │                                    │                         
   │                                            │             │                                    ▼                         
   │                                            │             │                 ┌─────────────────────────────────────┐      
   └────────────────────────────────────────────┘             │                 │             neos/setup              │      
                                                              │                 │                                     │      
                                                              │                 │         requires neos/flow          │      
                                                              │                 │   flow specific steps (database)    │      
                                                              │                 │                                     │      
                                                              │                 │      gui setup infrastructure       │      
                                                              │                 │  (backend/configuration/frontend)   │      
                                                                                │                                     │      
                                                                                └─────────────────────────────────────┘      
                                                                                                                             
                                                                                                                             
                                                                                                                             
                                                                                                                             
                                                                                                                             
```

### proposed

```
                                                                                                                             
                                                                       ┌────────────────────────────────────────────────────┐
                                                                       │                 neos/neos-setup v3                 │
                                                                       │                                                    │
                                                                       │                 requires neos/neos                 │
                                                                       │                                                    │
                                                                       │       cli commands for `setup:imagehandler`        │
                                                                       │                                                    │
                                                                       │              health check extensions:              │
                                                    ┌ ─ ─ ─ ─ ─ ─ ─ ─ ▶│                                                    │
                                                                       │      - (neos escr setup status in version v4)      │
                                                    │                  │          - at least one neos user exists           │
                                              neos specific            │ - image handling configured? And is it the optimal │
  ┌──────────────────────────────┐         commands extracted          │                        one?                        │
  │                              │                                     │                   - site exists                    │
  │        neos/cli-setup        │        - setup:imagehandler         │                                                    │
  │                              │                                     └────────────────────────────────────────────────────┘
  │     will be split up and     │─ ─ ─ ─ ┬ ─ ─ ─ ─ ┘                                             │                          
  │          deprecated          │                                                                │                          
  │                              │        │                                                       │                          
  └──────────────────────────────┘                                                                │                          
                                          │                                                       │                          
                                                                                       ┌─requires─┘                          
                                          │                                            │                                     
                               flow specific commands                                  │                                     
                                      extracted                                        │                                     
                                                                                       │                                     
                                      - welcome                                        ▼                                     
                                  - setup:database  ┌────────────────────────────────────────────────────────────────────┐   
                                          │         │                             neos/setup                             │   
                                                    │                                                                    │   
                                          │         │                         requires neos/flow                         │   
                                                    │                                                                    │   
                                          │         │      `flow welcome` deprecated and becomes `flow healthcheck`      │   
                                                    │                                                                    │   
                                          │         │                 cli command `flow setup:database`                  │   
                                                    │                                                                    │   
                                          └ ─ ─ ─ ─▶│    health check infrastructure (backend/configuration/frontend)    │   
                                                    │                                                                    │   
                                                    │                                                                    │   
                                                    │                    flow specific health checks:                    │   
                                                    │                - db connection (and good collation)                │   
                                                    │                    - doctrine migration status                     │   
                                                    │                  - php version web and cli match                   │   
                                                    │                                                                    │   
                                                    └────────────────────────────────────────────────────────────────────┘   
```






Technical implementation:
route: neos/setup -> configurable?
Middleware
no authentication (!!!no security relevant pieces of information)
neos/setup can be uninstalled
CLI endpoint for health check
Health check information (on the web it is basically a manual e2e test):

icon configuration in configuration
color based on Message
Health check extensible and configurable

```
interface Healthcheck
{
  public function excecute(): Message; // flow error message dtos
}
```

**Comment by mhsdesign** [comment]
Todos:

- [ ] adjust base distribution

**Comment by mhsdesign** [comment]
As written in slack:

the new setup/healthcheck dingsbums is now ready to be tested: https://github.com/neos/setup/pull/59

it would be great to see if it works also on "your maschine" and if it would help setting up a neos from scratch.

if we find the tool stable enough my plan is:
- release neos/setup@6 neos/neos-setup@3
- use the new setup in the base distributions for neos 8.3
- remove NeosCLi setup from dev-collection and upmerge
  - convert repo into abandoned standalone repo and tell packagist its abandoned
- create blogpost & video
- adjust https://docs.neos.io/guide/installation-development-setup/running-the-setup-tool

later todos:
- make a 9.0 compatible version of neos/neos-setup (version 4) release neos/neos-setup@4
- use the new setup in the base distributions for neos 9.0


~... well there is one known cache invalidation bug: the db settings cache are not emptied so updating the db connection doesnt let the check pass~

**Comment by mhsdesign** [comment]
Issues I had (on windows):

- [x] https://github.com/neos/flow-development-collection/pull/3045
- [x] one needs to do hacky things already to get flow running like admin shell and cache warmup (https://github.com/neos/flow-development-collection/pull/3106)
  - [x] should flow setup check the file permissions and resource publishing if it would work?, or even tell to do so explicitly on windows? check if the correct privilege is set on windows.
    - [x] we can check if the static collection is using the `FileSystemSymlinkTarget` and then check if  `symlink` is allowed (or via `whoami /priv`). and else warn to call `flow resource:publish static` in admin mode or activate the privilege
- [x] ~here should be a command to setup the php based on the one found or specified~
- [x] doctrine migrate is that slow that the page will refresh and run into an error because doctrine is not yet migrated 😅 (missing table…) - find out if migration is pending
- [x] show flow as .\flow.bat
  - [ ] show flow command as `flow` if oh-my-zsh plugin is installed?
    - [ ] on cli, we can actually see how it was invoked technically and propose the same string ^^ 
    - [ ] implementation: https://github.com/neos/setup/pull/59/commits/e298fab93e029b952cd876ab5a75b9c1eca6cdf4 
- [x] No supported image handler found exception … implement try catch against every healthcheck
- [x] show warning if gd is used at its only supposed to be for development. ~(Maybe depending on the context?)~
- [ ] if compile time checks are done the ui has no indicator that more is loading, and the runtime checks can take a long time after compiling
- [ ] phpPathAndBinary should default to `%PHP_BINARY%` so that at least flow server run and flow configuration show works:  https://github.com/neos/flow-development-collection/issues/3111
  - [ ] if we dont want this in flow, the setup command could use the current  `%PHP_BINARY%`  and write it into the settings
- [ ] show a quick tip like `composer update && composer dump-autoload && flow flow:cache:flush && flow flow:package:rescan && flow cache:warmup` ? in case something is really wrong? ^^
   - [ ] or find more issues directly like:
     - [ ] check if doctrine compiled correctly? `Warning: require(Doctrine/Proxies/__CG__.php): Failed to open stream: No such file or directory` (occurred before flow site import)
       - [ ] check `$objectConfigurationCache->has('doctrineProxyCodeUpToDate') === true`?
- [x] make it php 8.0 compatible? -> i just saw what php 5 was like and decided to not cry about 8.0 ;)
  - [x] yes: base distribution could easily require exact version: No confusion about availabilty.
  - [x] con: enums are sexy and we soon will only have to maintain php 8.2 code with neos 9.0 so php 8.0 might already get old :P - how many new projects use php 8.0?
- [ ] ux: tell the user in the web endpoint to also checkout the cli endpoint alternatively and reverse. Also at the web endpoint inform that this will pool every 10 s new status.
  - [ ] discuss auto refresh - uncool when there are always logs written and reference codes change :/ - just disable?
- [x] remove checks that are never run, because the bootstrap enforces them see \Neos\Flow\Core\Bootstrap::ensureRequiredEnvironment (like the docblock thing)
- [x] contribute `checkPhpBinaryVersion` code back to flow?
  - [x] avoid getting trapped during exec call on fast cgi binary
  - [x] https://github.com/neos/flow-development-collection/pull/3116 
- [x] `message was copied` visual bug when reloading
- [x] endpoints retriggered without waiting for response
- [ ] explain that copy doesnt work on non https - i was fooled too
- [ ] documentation about how we build this package (for maintaining)
- [ ] maybe remove redirect commands, because composer wont let you install it side by side with an old dev collection
- [x] remove Neos.CliSetup
  - [x] remove split job
  - [x] abandon package
  - [x] archive repo
  - [x] adjust readme

**Comment by mhsdesign** [comment]
<details>

When the `neos/setup` package is installed afterwards into a flow installation the configuration manager doesnt work correctly:

```
PHP Fatal error:  Uncaught TypeError: Neos\Setup\Infrastructure\HealthChecker::__construct(): Argument #2 ($configuredHealthchecks) must be of type array, null given, called in /Users/marchenryschultz/Code/core/Neos.NeosIo/Packages/Application/Neos.Setup/Classes/RequestHandler/SetupCliRequestHandler.php on line 103 and defined in /Users/marchenryschultz/Code/core/Neos.NeosIo/Packages/Application/Neos.Setup/Classes/Infrastructure/HealthChecker.php:17
Stack trace:
#0 /Users/marchenryschultz/Code/core/Neos.NeosIo/Packages/Application/Neos.Setup/Classes/RequestHandler/SetupCliRequestHandler.php(103): Neos\Setup\Infrastructure\HealthChecker->__construct(Object(Neos\Flow\Core\Bootstrap), NULL, Object(Neos\Setup\Domain\HealthcheckEnvironment))
#1 /Users/marchenryschultz/Code/core/Neos.NeosIo/Packages/Application/Neos.Setup/Classes/RequestHandler/SetupCliRequestHandler.php(192): Neos\Setup\RequestHandler\SetupCliRequestHandler->indexCommand()
#2 /Users/marchenryschultz/Code/core/Neos.NeosIo/Packages/Framework/Neos.Flow/Classes/Core/Bootstrap.php(112): Neos\Setup\RequestHandler\SetupCliRequestHandler->handleRequest()
#3 /Users/marchenryschultz/Code/core/Neos.NeosIo/Packages/Framework/Neos.Flow/Scripts/flow.php(71): Neos\Flow\Core\Bootstrap->run()
#4 /Users/marchenryschultz/Code/core/Neos.NeosIo/flow(18): require('/Users/marchenr...')
#5 {main}
  thrown in /Users/marchenryschultz/Code/core/Neos.NeosIo/Packages/Application/Neos.Setup/Classes/Infrastructure/HealthChecker.php on line 17

Fatal error: Uncaught TypeError: Neos\Setup\Infrastructure\HealthChecker::__construct(): Argument #2 ($configuredHealthchecks) must be of type array, null given, called in /Users/marchenryschultz/Code/core/Neos.NeosIo/Packages/Application/Neos.Setup/Classes/RequestHandler/SetupCliRequestHandler.php on line 103 and defined in /Users/marchenryschultz/Code/core/Neos.NeosIo/Packages/Application/Neos.Setup/Classes/Infrastructure/HealthChecker.php:17
Stack trace:
#0 /Users/marchenryschultz/Code/core/Neos.NeosIo/Packages/Application/Neos.Setup/Classes/RequestHandler/SetupCliRequestHandler.php(103): Neos\Setup\Infrastructure\HealthChecker->__construct(Object(Neos\Flow\Core\Bootstrap), NULL, Object(Neos\Setup\Domain\HealthcheckEnvironment))
#1 /Users/marchenryschultz/Code/core/Neos.NeosIo/Packages/Application/Neos.Setup/Classes/RequestHandler/SetupCliRequestHandler.php(192): Neos\Setup\RequestHandler\SetupCliRequestHandler->indexCommand()
#2 /Users/marchenryschultz/Code/core/Neos.NeosIo/Packages/Framework/Neos.Flow/Classes/Core/Bootstrap.php(112): Neos\Setup\RequestHandler\SetupCliRequestHandler->handleRequest()
#3 /Users/marchenryschultz/Code/core/Neos.NeosIo/Packages/Framework/Neos.Flow/Scripts/flow.php(71): Neos\Flow\Core\Bootstrap->run()
#4 /Users/marchenryschultz/Code/core/Neos.NeosIo/flow(18): require('/Users/marchenr...')
#5 {main}
  thrown in /Users/marchenryschultz/Code/core/Neos.NeosIo/Packages/Application/Neos.Setup/Classes/Infrastructure/HealthChecker.php on line 17

```

after running `flow configuration:show --path Neos.Setup` it the configuration manager returns the expected results.


```
        /** @var PackageManager $packageManager */
        $packageManager = $bootstrap->getEarlyInstance(PackageManager::class);

        $packageManager->rescanPackages();
```


but the rescan should already be done by this hook
```
\Neos\Flow\Composer\InstallerScripts::postUpdateAndInstall
```

</details>

edit: this might also be fixed via https://github.com/neos/flow-development-collection/pull/3045

**Comment by mhsdesign** [comment]
TODOs

- close issues
- update docs neos io
- neos 9 version of neos/neos-setup

**Comment by skurfuerst** [comment]
@mhsdesign can we close this?

**Comment by mhsdesign** [comment]
Long due to be closed as its a fairly standard tool to use now <3 ... 3 Years later. LOL. Time.
